# Site settings
title: Ewan Klein GitHub Projects
email: 
description: 
baseurl:
url: "http://ewan-klein.github.io"
twitter: ewanhklein
github: ewan-klein

# Build settings
markdown: kramdown
permalink: pretty

highlighter: pygments