# Site settings
title: Ewan Klein GitHub Projects
email: ewan@raw-text.io
description: 
baseurl:
url: "http://ewan-klein.github.io"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: pygments