# Site settings
title: Ewan Klein
email: ewan@raw-text.io
description: 
baseurl:
url: "http://www.raw-text.io"
twitter: ewanhklein
github: ewan-klein

# Build settings
markdown: kramdown
permalink: pretty

highlighter: pygments